In [1]:
import tensorflow as tf

# 즉시실행모드인지 확인
print(tf.executing_eagerly())

True


In [5]:
a = 1 
b = 2 
c = tf.math.add(a,b)

c
c.numpy()

3

In [ ]:
# 케라스 제공
# 자동미분 
# 예측과 실제값과의 오차를 최소로 하는 함수식을 찾기위해 미분하는 과정이 필요

In [10]:
# 스칼라

a = tf.constant(1)
print(a)
print(tf.rank(a))   # 객체의 차수 확인

# 자료형 변환
a = tf.cast(a,tf.float32)
print(a.dtype)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
<dtype: 'float32'>


In [15]:
# 사칙연산

a = tf.constant(2)
b = tf.constant(3)
c = tf.add(a,b)
print(c)
d = tf.subtract(a,b)
print(d)
e = tf.multiply(a,b)
print(e)
f = tf.divide(a,b)
f1 = tf.math.divide(a,b)
print(f)
print(f1)

#나머지
g = tf.math.mod(a,b)
print(g)

#몫
h = tf.math.floordiv(a,b)
print(h)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(0.6666666666666666, shape=(), dtype=float64)
tf.Tensor(0.6666666666666666, shape=(), dtype=float64)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [23]:
import numpy as np

# 1차원 배열
py_list = [10., 20., 30.]   # 파이썬 리스트
num_arr = np.array([10.,10.,10.])   # 넘파이 배열

# 텐서로 변환

vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

print(vec1)
print(vec2)

# 파이썬 리스트배열은 tf.constant를 사용한 정수 변환이 어렵다.
# 리스트를 먼저 정수로 변환한 뒤 텐서로의 변환이 가능함 


print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [30]:
# 벡터연산

add2 = vec1 + vec2
add2

print(tf.math.sqrt(add2))
print(tf.math.divide(vec1,vec2))


# 합계구하기 : 벡터를 구성하는 원소들의 합계를 구할 수 있다. 
# 합계는 스칼라로 표현됨

print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))
print(tf.reduce_sum(vec1+vec2))

# 브로드캐스팅 연산

print(vec1 + 1)

tf.Tensor([4.472136  5.477226  6.3245554], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)
tf.Tensor(90.0, shape=(), dtype=float32)
tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)


In [39]:
# 행렬

matrix = [[10,20],
          [30,40]]

mat1 = tf.constant(matrix)
print(f'mat1 : {mat1}')

tf.rank(mat1)


vec1 = [10,20]
vec2 = [30,40] 
# stack함수로 1차원배열을 위아래로 쌓기 
mat2 = tf.stack([vec1, vec2])
print(f'mat2 : {mat2}')

# 행렬곱연산

mat_mul = tf.matmul(mat1, mat2)
print(f'행렬곱 : {mat_mul}')



# 행렬곱계산 
# 첫번쨰행 첫번째열
# 첫번쨰행 두번쨰열
# 두번째행 첫번째열
# 두번째행 두번째열

mat1 : [[10 20]
 [30 40]]
mat2 : [[10 20]
 [30 40]]
행렬곱 : [[ 700 1000]
 [1500 2200]]


In [43]:
# 3차원 텐서

mat1 = [[1,2,3,4],[5,6,7,8]]
mat2 = [[9,10,11,12],[13,14,15,16]]
mat3 = [[17,18,19,20],[21,22,23,24]]

tensor1 = tf.constant([mat1,mat2,mat3])
print(f'3차원 텐서 : {tensor1}')
print(f'shape : {tensor1.shape}')
print(f'rank : {tf.rank(tensor1)}')

3차원 텐서 : [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
shape : (3, 2, 4)
rank : 3


In [45]:
tensor2 = tf.stack([mat1,mat2,mat3])
print(f'stack으로 쌓은 3차원텐서 : {tensor2}' )


stack으로 쌓은 3차원텐서 : [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [51]:
# 4차원 텐서

tensor_rank_4 = tf.stack([tensor1,tensor2])
print(f'4차원텐서 : {tensor_rank_4}')
print(tensor_rank_4.shape)
print(tf.rank(tensor_rank_4))

4차원텐서 : [[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]]
(2, 3, 2, 4)
tf.Tensor(4, shape=(), dtype=int32)


In [54]:
# 3차원 텐서 인덱싱 

print(tensor1)

tensor1[0,1,1]

# 23,24 출력하기 
tensor1[-1,-1,2:]

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([23, 24])>

In [63]:
# 형태변환
# 텐서의 형태변환은 넘파이 reshape 함수의 사용법과 비슷

tensor = tf.constant(range(0,24))
print(tensor)

# 1차원 배열을 2차원으로 변환
tensor1 = tf.reshape(tensor, [3,8])
print(tensor1)

# 행 지정해서 변환
tensor2 = tf.reshape(tensor1, [-1,4])
print(tensor2)

# 2차원행렬을 다시 1차원으로
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)


# 1차원 벡터를 3차원 텐서로
tensor_vec = tf.reshape(tensor, [-1,3,4])
print(tensor_vec)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [70]:
# 변수

# 수많은 미분 연산산을 반복하면서 각각의 중간 연산결과를 저장할 때 변수를 이용한다.
# 모델을 학습하는 중간단계마다 모델의 가중치 행렬을 변수에 저장하고, 계산을 반복하면서 변수의 값을 업데이트

tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)
print(tensor_var1.shape)

print(tensor_var1.name)
print(tensor_var1.numpy)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
(2, 3)
Variable:0
<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>>


In [73]:
# 변수 수정

tensor_var1.assign([[7,8,9],[10,11,12]])
print(tensor_var1.numpy())

tensor_var1.assign_add([[1,2,3],[4,5,6]])
print(tensor_var1.numpy())

print(tensor_var1
      )

[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]])>


In [76]:
# 텐서플로 변수 -> 텐서

tensor_again = tf.convert_to_tensor(tensor_var1)
print(tensor_again.numpy())
print(tensor_again)

[[ 8 10 12]
 [14 16 18]]
tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)


In [80]:
# 자동미분

# 데이터셋 생성
# 시드값을 지정하여 Generator 생성
g = tf.random.Generator.from_seed(2020)
print(g)
x = g.normal(shape = (10,))
y = 3 * x + 2

print(x)
print(y)

tf.Tensor(
[-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ], shape=(10,), dtype=float32)
tf.Tensor(
[1.3716869 5.8239574 5.6396422 1.4726914 7.630952  2.4913976 5.246735
 3.85999   0.6679337 5.914503 ], shape=(10,), dtype=float32)


In [81]:
# 손실함수 정의

def cal_mse(X,Y,a,b):
    Y_pred = a * X + b 
    squared_error = (Y - Y_pred)**2
    mean_squared_error = tf.reduce_mean(squared_error)
    
    return mean_squared_error

In [84]:
# tf.GradientTape로 자동 미분 과정을 기록

a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHE = 200

for epoch in range(EPOCHE):
    with tf.GradientTape() as tape:
        mse = cal_mse(x, y, a, b)
    
    grads = tape.gradient(mse, {'a': a, 'b': b})
    d_a, d_b = grads['a'], grads['b']
        
    a.assign_sub(d_a * 0.05)
    b.assign_sub(d_b * 0.05)
    
    if epoch % 20 == 0:
        print(f'epoch : {epoch+1}, loss : {mse.numpy()} , a : {a.numpy()}, b : {b.numpy()}')

epoch : 1, loss : 21.206811904907227 , a : 0.43943047523498535, b : 0.40119490027427673
epoch : 21, loss : 0.05340142920613289 , a : 2.7137272357940674, b : 2.184020519256592
epoch : 41, loss : 0.010097725316882133 , a : 2.88142466545105, b : 2.1174652576446533
epoch : 61, loss : 0.0025486552622169256 , a : 2.9410433769226074, b : 2.0596706867218018
epoch : 81, loss : 0.0006438164855353534 , a : 2.9703845977783203, b : 2.0300068855285645
epoch : 101, loss : 0.00016263902944047004 , a : 2.9851152896881104, b : 2.0150821208953857
epoch : 121, loss : 4.108121356694028e-05 , a : 2.9925191402435303, b : 2.007580041885376
epoch : 141, loss : 1.037863694364205e-05 , a : 2.9962399005889893, b : 2.003809928894043
epoch : 161, loss : 2.6213424462184776e-06 , a : 2.998110055923462, b : 2.0019147396087646
epoch : 181, loss : 6.618389534196467e-07 , a : 2.9990503787994385, b : 2.000962257385254
