In [1]:
import tensorflow as tf
import pandas as pd

In [81]:
# 1. 데이터를 준비

(x_train,y_train), _ = tf.keras.datasets.mnist.load_data()
print(x_train.shape, y_train.shape)
#(60000, 28, 28) (60000,)

# x_train = x_train.reshape(60000,784)
y_train = pd.get_dummies(y_train)

print(x_train.shape, y_train.shape)
print(_)


(60000, 28, 28) (60000,)
(60000, 28, 28) (60000, 10)
(array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 

In [92]:
#2. 모델을 만든다.
x = tf.keras.layers.Input(shape = [28,28])
f = tf.keras.layers.Flatten()(x)
h = tf.keras.layers.Dense(84, activation = 'relu')(f)
y = tf.keras.layers.Dense(10, activation = 'softmax')(h)

model = tf.keras.models.Model(x,y)

model.compile(loss='categorical_crossentropy', metrics = ['accuracy'])

(60000, 28, 28) (60000, 10)
(60000, 28, 28) (60000, 10)
(60000, 28, 28) (60000, 10)
(60000, 28, 28) (60000, 10)


In [93]:
print(x_train.shape, y_train.shape)

(60000, 28, 28) (60000, 10)


In [95]:
#3. 모델을 학습
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9288 - loss: 0.4744
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9389 - loss: 0.4129
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9453 - loss: 0.3744
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9509 - loss: 0.3411
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9533 - loss: 0.3332


In [96]:
#4. 예측

import numpy as np
prediction = model.predict(x_train[0:5])
# print(np.round(prediction,2))

for i in prediction:
    rediction_rounded = np.round(i, 2)
    prediction_easy = np.argmax(rediction_rounded)
    print(f' {rediction_rounded} = {prediction_easy}')
    
    
print(y_train[0:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] = 5
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] = 0
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] = 4
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] = 1
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] = 9
       0      1      2      3      4      5      6      7      8      9
0  False  False  False  False  False   True  False  False  False  False
1   True  False  False  False  False  False  False  False  False  False
2  False  False  False  False   True  False  False  False  False  False
3  False   True  False  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False  False  False   True
